### ISSUE TITLE
Discussion: BTRFS causes issues with /swapfile

### ISSUE THREAD

**Issue by Nick-Shadow** [ChrisTitusTech/ArchTitus#101]
On my fork and branch, I am currently working on adding a swapfile with not only low ram detection but also allows user input to expand the size of the swap. I keep on getting this message after I run:
`$ swapon /swapfile`
`swapon: swapfile2: swapon failed: Invalid argument`

I have tried running this manually, but alas, I get the same thing.

Stack Exchange says BTRFS is the problem. I feel like we should move to ext4, it is much more standard. But if we can get the swapfile working on BTRFS then, that's nice too. 

[https://superuser.com/questions/539287/swapon-failed-invalid-argument-on-a-linux-system-with-btrfs-filesystem](url)

Have you experience similar issues.

**Comment by Nick-Shadow** [comment]
![image](https://user-images.githubusercontent.com/60942351/141535059-f83a2c92-5981-49bb-9c9c-554d41db1383.png)
I got a pic.

**Comment by yehonatan2020** [comment]
did you do chmod 600?

**Comment by yehonatan2020** [comment]
Here's what I do to make a swapfile (and I had this working on btrfs)...

fallocate -l 8GB /opt/swap/swapfile
chmod 600 /opt/swap/swapfile
mkswap /opt/swap/swapfile
swapon /opt/swap/swapfile
echo "/opt/swap/swapfile   none   swap   defaults   0 0" >>  /etc/fstab

**Comment by Nick-Shadow** [comment]
Unfortunately fallocate is deprecated from what I can find, so I didn't want to use that.

**Comment by ChrisTitusTech** [comment]
This should be fixed with latest commit.
