### ISSUE TITLE
Trying out in VirtualBox

### ISSUE THREAD

**Issue by mrehanabbasi** [ChrisTitusTech/ArchTitus#102]
I'm trying to install the OS as a VM in VirtualBox but it reboots after entering the disk name. I'm using the EFI boot option. After rebooting, if I boot into Arch Linux from ISO, I repeat the same thing all over again. The other option is an EFI Shell in which booting from bootx64.efi takes me back to the Arch Linux selection menu.

**Comment by ChrisTitusTech** [comment]
Fixed in latest commit
