### ISSUE TITLE
Trying out in VMWare, no way to set resolution to higher that 800x600

### ISSUE THREAD

**Issue by menkaur** [ChrisTitusTech/ArchTitus#106]
I decided to try out the script on vmware with clean arch install. The resulting os doesn't let me change resolution to anything other than 800x600, neither in settings nor with xrandr. The options are there, but when I select them, the monitor reverts to 800x600 immediately

**Comment by marvinroman** [comment]
I had the same issue in Virtualbox. In Virtualbox you need to install Virtualbox Guest Additions into the VM operating system. I don't know if there is something similar in VMWare.

**Comment by meechgalhuquot** [comment]
See if you have different graphics controllers is VMWare, in VirtualBox just changing the graphics controller fixed that problem for me
