### ISSUE TITLE
Feature request: dvorak

### ISSUE THREAD

**Issue by menkaur** [ChrisTitusTech/ArchTitus#107]
I'm a dvorak user, and I really don't like using qwerty for typing. Before running the script, I used `loadkeys dvorak`, but than when I had to enter user name and password, it has reverted to qwerty for some reason, and than the end installation had qwerty as default. Can you at least give the user a choice?
Also, if you use dvorak, please use https://github.com/prog666/dvorak-qwerty instead of stock version. Problem with stock version is that it overrides qwerty shortcuts, and they are more convenient than the same shortcuts when mapped in dvorak

**Comment by ChrisTitusTech** [comment]
Added support for this on start.
