### ISSUE TITLE
Username error

### ISSUE THREAD

**Issue by plgmorris** [ChrisTitusTech/ArchTitus#109]
While installing on VirtualBox with Arch Linux release 2021.11.01 kernel 5.14.15, errors occurred after entering username "Patrick". Screenshot attached. If however, I put all lowercase "patrick" it all works fine.

The consequence of this is that it then misses a lot of the scripting before the reboot. After the reboot, it tells me to choose a user and enter my password but there is no user to select so therefore I cannot log in. Second screenshot shows this.
![Screenshot 2021-11-13 204433](https://user-images.githubusercontent.com/49840135/141658678-a789a1c5-bc97-4dad-83ee-841e61fc4ffd.png)
![Screenshot 2021-11-13 204844](https://user-images.githubusercontent.com/49840135/141658679-d6d1b084-521c-46c2-9775-e070c790de3b.png)

**Comment by oguh43** [comment]
same issue :D
![image](https://user-images.githubusercontent.com/13382592/141696773-22f2b090-72bc-484c-99b8-d4471cfd25a3.png)

**Comment by oguh43** [comment]
> While installing on VirtualBox with Arch Linux release 2021.11.01 kernel 5.14.15, errors occurred after entering username "Patrick". Screenshot attached. If however, I put all lowercase "patrick" it all works fine.
> 
> The consequence of this is that it then misses a lot of the scripting before the reboot. After the reboot, it tells me to choose a user and enter my password but there is no user to select so therefore I cannot log in. Second screenshot shows this. ![Screenshot 2021-11-13 204433](https://user-images.githubusercontent.com/49840135/141658678-a789a1c5-bc97-4dad-83ee-841e61fc4ffd.png) ![Screenshot 2021-11-13 204844](https://user-images.githubusercontent.com/49840135/141658679-d6d1b084-521c-46c2-9775-e070c790de3b.png)

The regex validating usernames is `^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\$)$` so you cant have uppercase names...

**Comment by ChrisTitusTech** [comment]
Fixed with new commit
