### ISSUE TITLE
Can’t install on drive, potentially package errors?

### ISSUE THREAD

**Issue by TriggerMoke** [ChrisTitusTech/ArchTitus#110]
After I tell it to format a drive it errors out with "failed to install packages to new root"
Also
"Failed to run command /root/ArchTitus/1-setup.sh"
Also
Up in the terminal is some errors about how core.db, extra.db, community.db failed to download

![image](https://user-images.githubusercontent.com/61124621/141670159-f7492393-5910-4dd0-810a-812d6f3b61b2.jpeg)

**Comment by ChrisTitusTech** [comment]
Fixed with new install script
