### ISSUE TITLE
Unable to install apps

### ISSUE THREAD

**Issue by CODER-AG** [ChrisTitusTech/ArchTitus#115]
Hi I am really new to archlinux I had used Ubuntu for some time but this is completely new for me...
When I try to install some app in it I get error that I must run it in root mode so I tried the way for Ubuntu sudo su...
But I am still getting error and apt is also giving error

**Comment by 71Zombie** [comment]
Arch doesn't use apt, this uses pacman and yay

**Comment by treatmeniceplz** [comment]
that is true only debian or ubuntu based distros use apt

**Comment by WitherCubes** [comment]
> that is true only debian or ubuntu based distros use apt

Yes, Debian and Ubuntu uses apt, and Arch Linux uses pacman as it's package manager.

**Comment by treatmeniceplz** [comment]
I actually used Debian and Ubuntu before so yea

**Comment by D1VY4NSHU** [comment]
For installing packages, you should use
"sudo pacman -Sy (package name)"

**Comment by treatmeniceplz** [comment]
Your right

**Comment by ChrisTitusTech** [comment]
Hehe, just saw this issue, reminded me of watching Linus do this exact thing! Closing the issue.
