### ISSUE TITLE
wont install in virtualbox

### ISSUE THREAD

**Issue by treatmeniceplz** [ChrisTitusTech/ArchTitus#117]
on the disk select part in the script the install crashes

**Comment by D1VY4NSHU** [comment]
I used it on Virtualbox and it worked fine. Maybe you have selected a specific disk partition like "dev/sda1".
You need to select a disk. ie: /dev/sda/
hope it helps.

**Comment by mrehanabbasi** [comment]
I am facing the same issue (#102). It persists in VMware Player as well.

**Comment by mrehanabbasi** [comment]
> I used it on Virtualbox and it worked fine. Maybe you have selected a specific disk partition like "dev/sda1". You need to select a disk. ie: /dev/sda/ hope it helps.

Virtualbox only makes one disk i.e. /dev/sda. Can you walk us through the steps and configuration of the VM you set up?

**Comment by treatmeniceplz** [comment]
I will try again today

**Comment by treatmeniceplz** [comment]
Does the fact I used a nvme controller for the drive cause anything

**Comment by mrehanabbasi** [comment]
> Does the fact I used a nvme controller for the drive cause anything
> 
> > On 19 Nov 2021, at 9:05 AM, David Dobrzycki ***@***.***> wrote:
> > 
> > ﻿
> > I will try again today 
> > 
> >>> On 19 Nov 2021, at 8:18 AM, Muhammad Rehan Abbasi ***@***.***> wrote:
> >>> 
> >> ﻿
> >> I used it on Virtualbox and it worked fine. Maybe you have selected a specific disk partition like "dev/sda1". You need to select a disk. ie: /dev/sda/ hope it helps.
> >> 
> >> Virtualbox only makes one disk i.e. /dev/sda. Can you walk us through the steps and configuration of the VM you set up?
> >> 
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Don't know. I used the default one and it didn't work. Haven't tried changing that.

**Comment by D1VY4NSHU** [comment]
For me it worked fine when I selected sda on the disk selection. However, I wasn't able to log in to kde, after entering the password, nothing happened at all. It wasn't even hanging there, just nothing happening. So I had to remove the arch and install it from "archinstall" command from the arch iso.

**Comment by treatmeniceplz** [comment]
That’s wierd can you make a new issue or is this in a way related

**Comment by treatmeniceplz** [comment]
i noticed i am just dumb and forgot /dev/
