### ISSUE TITLE
Locale not configured correctly after install

### ISSUE THREAD

**Issue by ondrish** [ChrisTitusTech/ArchTitus#124]
Hi Chris, 

after installation, when I run kitty, the shell profile is not correctly set up in it. Also, I noticed LANG=C in the locales, this should be used for testing purpouses only, right?

for example, when I run btop from kitty, it complains my UTC config is not correct nad must use --force-utc to launch it. Konsole has no such issues. 

Also, fonts are not consistently used in kitty, some were missing. again, konsole works correctly. 

I changed your original US/CHicago settings to Europe/Bratislava and got the same problem multiple times. 

still awesome work and a great script set :)

**Comment by ChrisTitusTech** [comment]
This should now be fixed.
