### ISSUE TITLE
cant boot into arch

### ISSUE THREAD

**Issue by treatmeniceplz** [ChrisTitusTech/ArchTitus#125]
<img width="365" alt="bruh" src="https://user-images.githubusercontent.com/75908199/142728552-5e009809-b36b-4e34-97e0-cc3e2ae8ddd2.png">
the screenshot explains it all
dont mind the floppy drive it isnt in use

**Comment by daleshiift** [comment]
Getting the same issue

**Comment by vinodhmoodley** [comment]
Same for me. The script installs everything, asks for the usb to be removed but the system drive is not bootable.

**Comment by B4579** [comment]
Same for me didn't boot

**Comment by treatmeniceplz** [comment]
Gosh this is funny

**Comment by vinodhmoodley** [comment]
> Gosh this is funny
> […](#)

Do you mind explaining the joke to us? It’s pointless making a comment like this if you’re not actually contributing anything.

**Comment by treatmeniceplz** [comment]
The fact everyone is having this issue and I think this is a arch issue since Manjaro experiences the same issue

**Comment by zyurph** [comment]
I have tried this script on my dell latitude 5421 and it will not boot.  I have secure boot disabled and the storage set to AHCI/NVMe mode, and I'm not dual booting.  At first, I was set to Raid On mode and it failed with the error couldn't find the UUID, now with it set to AHCI it just stops at starting version 249.6-3-arch.  Also, I am installing it to my drive nvme0n1, not a partition.

**Comment by 71Zombie** [comment]
I believe after switching to grub is when it stopped working for me.

**Comment by antonyshen** [comment]
Do you guys enable UEFI boot?

**Comment by zyurph** [comment]
yes, and I have been and currently running pop-os just fine.

**Comment by treatmeniceplz** [comment]
No I can’t in virtualbox

**Comment by vinodhmoodley** [comment]
> Do you guys enable UEFI boot?

Yes. The system boots Ubuntu, macOS and Windows 11 in UEFI mode perfectly fine.

**Comment by treatmeniceplz** [comment]
hold it macOS are you doing this on a mac or is it a hackintosh

**Comment by vinodhmoodley** [comment]
> hold it macOS are you doing this on a mac or is it a hackintosh
> […](#)

It’s a regular PC that boots macOS using OpenCore 0.7.4.

**Comment by vinodhmoodley** [comment]
I tried the script on another PC and it worked perfectly. This PC has an ASUS motherboard with a 2700X AMD CPU. I’m not sure but it seems like the UEFI implementation on my MSI motherboard/9900K CPU system may be the issue.

**Comment by treatmeniceplz** [comment]
Might try VMware then with same specs

**Comment by treatmeniceplz** [comment]
This isn’t going anywhere in my opinion
