### ISSUE TITLE
Keyboard language preferences

### ISSUE THREAD

**Issue by VictorHachard** [ChrisTitusTech/ArchTitus#129]
Hi Chris,

I have an improvement idea to make. The script could automatically configures the language preference of the keyboard. (Not so easy to type english with a French keyboard :smile:).

Keep the good work.

**Comment by Spaanhede** [comment]
A quick fix is typing.
```
$> loadkeys fr
```
And then configuring the language and keybord layout on the desktop after installation.

**Comment by ChrisTitusTech** [comment]
Fixed this with the new update to support all keyboards for all languages.
