### ISSUE TITLE
ArchTitus doesn't use the recommended /boot partition size of 300MB

### ISSUE THREAD

**Issue by CrimsonXMC** [ChrisTitusTech/ArchTitus#131]
ArchTitus doesn't use the recommended /boot partition size of **at least** 300MB for UEFI systems. 
As noted on the Arch wiki, it is recommended that /boot be at least 300MB for UEFI systems and 200MB for legacy systems. The partition size ArchTitus uses is 100MB, at least every time I've installed it.

This has caused issues for me when trying to install Zen kernel as the boot partition is too small.

**Comment by yehonatan2020** [comment]
Nice. I also found this problem. I made mine 512mb, but yeah like you say 300mb should be fine

**Comment by ChrisTitusTech** [comment]
Updated in ArchTitus 2.0
