### ISSUE TITLE
Getting Epic Games Store and Battle.net working in Lutris

### ISSUE THREAD

**Issue by Wellwisher0001** [ChrisTitusTech/ArchTitus#136]
To get the Epic Games Store Working I had to follow the Nvidia driver instructions from Lutris ([link](https://github.com/lutris/docs/blob/master/InstallingDrivers.md))
And run the command: 

sudo pacman -S --needed nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader

Run to get the Battle.net connection working I had to run:

sudo sysctl -w net.ipv4.ip_default_ttl=80

Some games will require winetricks to have .Net or Visual C++ runtime installed.
Use winetricks to install dotnet472 vcrun2015 (command line works)

**Comment by ChrisTitusTech** [comment]
Added to Wiki Page
