### ISSUE TITLE
No Desktop Environment

### ISSUE THREAD

**Issue by Twikzer** [ChrisTitusTech/ArchTitus#137]
When it finish the install, and reboot, all the vm screen is black, with the text: "Starting version 249.7-2-arch"
and nothing happens.
I can access other tty, Ctrl+Alt+F[1-12], and login (terminal only)

Install on a VM, kvm with qemu
ArchTitus install on /dev/vda, with 50 Gb

Hots: Manjaro with kernel 5.14

startx:
"xf86EnableIO: failed to enable I/O port 0000-03ff (Operation not permitted)"
"Fatal server error: no screens found"
"xinit: giving up"
"xinit: unable to connect to X server: connection refused"
"xinit: server error"

I try check #6, #34, #71 and #42, but is still the same

**Comment by Zackptg5** [comment]
This isn't aimed towards vms and so doesn't install any of the graphics drivers needed for a vm: https://wiki.archlinux.org/title/QEMU#Enabling_SPICE_support_on_the_guest

**Comment by ChrisTitusTech** [comment]
This should be fixed with today's update

**Comment by JealousMaiden** [comment]
I still got the same issue.

- Fresh QEMU/KVM install on Zorin OS Host
- no changes on display/graphic settings
- drive: /dev/vda (50 GB)

Also got no prompt asking to select the desktop environment

![image](https://user-images.githubusercontent.com/77886477/150690432-239fa577-2953-49b9-997f-34bc3356ad89.png)

**Comment by stojshic** [comment]
For running in WM, I must remove xf86-video-qxl package after installation (ctrl+alt-f2 to go to different tty) and then it works. Or just remove xorg-drivers from pacman-pkgs.txt to not install it at all

**Comment by stojshic** [comment]
> For running in WM, I must remove xf86-video-qxl package after installation (ctrl+alt-f2 to go to different tty) and then it works. Or just remove xorg-drivers from pacman-pkgs.txt to not install it at all

For running in WM, I must remove xf86-video-qxl package after installation (ctrl+alt-f2 to go to different tty) and then it works. Or just remove xorg-drivers from pacman-pkgs.txt to not install it at all
