### ISSUE TITLE
Will virtualbox ever be compatible with this script

### ISSUE THREAD

**Issue by Minethegroud** [ChrisTitusTech/ArchTitus#145]
I really want to see this script in a vm but for some reason it's impossible for it to behave correctly as sometimes the username will have an error or the password wouldn't show up as a prompted and when you finally get to reboot virtualbox saids no operation system installed and like what, grub is so buggy in this. And I don't want to what 20 mins just to see if this script will succeed and not having to reset installation process, I'm not a programmer expert but I hope this script actually cleans up its bugs.

**Comment by treatmeniceplz** [comment]
This is a good idea because it won’t even boot into anything it just halts

**Comment by dvon88** [comment]
I have installed this in VBox probably 20+ times so far, and it has worked every time. Maybe there is an issue with your VBox setup as well? Not really sure, just throwing something out there

**Comment by xKuusou** [comment]
> as sometimes the username will have an error or the password wouldn't show up as a prompted 

Make sure you're typing your username in lowercase. The script does not correct this for you, and usernames need to be lowercase. The script will throw an error (username not found or something) and not actually finish properly. This could be your issue.

**Comment by treatmeniceplz** [comment]
> I have installed this in VBox probably 20+ times so far, and it has worked every time. Maybe there is an issue with your VBox setup as well? Not really sure, just throwing something out there

Might try again tommorow

**Comment by ChrisTitusTech** [comment]
Big commit that works with every VM I tried. Arch Titus 2.0 released today.
