### ISSUE TITLE
Allow pooling into one btrfs filesystem

### ISSUE THREAD

**Issue by chrishazfun** [ChrisTitusTech/ArchTitus#153]
I have two nVME SSDs on my system and was wondering if there was a way to adjust the script to accommodate that, maybe a way to detect a comma-separated list of devices, I have absolutely no idea how to do this lol

**Comment by ChrisTitusTech** [comment]
Very cool idea, I'm not sure how I could script this as it will vary greatly from setup to setup. Possibly doing a LVM setup that leaves the door open for you to manually do this

**Comment by chrishazfun** [comment]
Script could detect space/comma separated lists when asking for devices to install ArchTitus to, the order might play a part too and will have to be mentioned in the lsblk prompt beforehand, something like "Where would you like to install this? (/dev/sda for example, ordered space/comma separated list for automatic LVM setup)"
