### ISSUE TITLE
Fix NVMe install 

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#155]
Chris, I noticed an error, when trying to install on NVMe. These 3 lines....
mkfs.vfat -F32 -n "EFIBOOT" "${DISK}2"
mkfs.btrfs -L "ROOT" "${DISK}3" -f
mount -t btrfs "${DISK}3" /mnt
should be....
mkfs.vfat -F32 -n "EFIBOOT" "${DISK}p2"
mkfs.btrfs -L "ROOT" "${DISK}p3" -f
mount -t btrfs "${DISK}p3" /mnt

**Comment by fhanrath** [comment]
This is already fixed in the [test branch](https://github.com/ChrisTitusTech/ArchTitus/blob/test/0-preinstall.sh).

But I'm not sure when it will be merged into the main branch.

**Comment by ChrisTitusTech** [comment]
Merged test to main today for ArchTitus 2.0
