### ISSUE TITLE
Bug: Fails to install on BIOS(LEGACY) VMs - Unable to boot after install.

### ISSUE THREAD

**Issue by atdtn** [ChrisTitusTech/ArchTitus#16]
After successful install, the system doesn't boot.

<img width="1136" alt="Screenshot 2021-10-24 at 12 51 01" src="https://user-images.githubusercontent.com/12551051/138590846-fcca61a4-4be5-49e5-bda8-0d8e80c171ed.png">
<img width="1136" alt="Screenshot 2021-10-24 at 12 52 30" src="https://user-images.githubusercontent.com/12551051/138590850-c76e0a7b-6476-4792-a6c2-97573613940a.png">

**Comment by ChrisTitusTech** [comment]
Updated to GRUB and allows both EFI and Legacy boot
