### ISSUE TITLE
Unresponsive/Laggy GUI Items

### ISSUE THREAD

**Issue by sanegaming** [ChrisTitusTech/ArchTitus#160]
It seems the priority of the main desktop experience is lower than other tasks, for example, while downloading a steam game I cannot switch tabs as it is using full focus to download things. Same is true when installing large packages via AUR / console tasks.

This happens nearly every time and its getting quite frustrating.

**Comment by ChrisTitusTech** [comment]
Just did a new commit that should solve this.

**Comment by sanegaming** [comment]
Thanks, is there an update script I could run to solve this without re-installing?
