### ISSUE TITLE
Getting this error after installing 

### ISSUE THREAD

**Issue by Arnab11** [ChrisTitusTech/ArchTitus#162]
installed 2times using the script. after reboot got this same error messege both time. Any solutions? 

![PXL_20220107_135910408](https://user-images.githubusercontent.com/25551878/148515534-7342f1d0-6df5-4bd0-829c-48bf81e471e3.jpg)

**Comment by ChrisTitusTech** [comment]
There was a disk error in setup script should be fixed now
