### ISSUE TITLE
Arch freeze on boot after finishing the installation

### ISSUE THREAD

**Issue by thanantonop** [ChrisTitusTech/ArchTitus#165]
Hi,

I tried yesterday to install the Arch Titus on your final commit. The installation finished successful but I saw that it didn't installed nothing from AUR during Installation. Also when I tried to boot to Arch was freeze on the black screen with Arch version 250 if I remember well.
I did the installation in two laptops twice with the same result.
I was able to install it with no problem on your previous scripts before you done the last changes yesterday.

**Comment by khaneliman** [comment]
I have always had the same behavior trying to get this to work in a VM. When I remove the quiet flag from grub, it is just stopped blinking cursor after 

> Reached target Multi-User System
>  Reached target Graphical Interface
>  Started Hostname Service

**Comment by ChrisTitusTech** [comment]
Found error with $USERNAME var that is now fixed and I believe it was causing this.
