### ISSUE TITLE
No sound option in System Settings

### ISSUE THREAD

**Issue by Counterpoint86** [ChrisTitusTech/ArchTitus#167]
Sound configuration options appear to be missing within System Settings. The solution appears to be adding the plasma-pa package to enable the Audio section under Hardware.

**Comment by Zackptg5** [comment]
It's there (listed in aur-packages.txt), just not getting installed. See this issue: https://github.com/ChrisTitusTech/ArchTitus/issues/168

**Comment by yehonatan2020** [comment]
I have the plasma-pa in the pacman packages list. I dont know why to use it from the aur instead of pacman

**Comment by Zackptg5** [comment]
Good point, it should be in the pacman-pkgs.txt instead of aur-pkgs.txt

**Comment by ChrisTitusTech** [comment]
Fixed!
