### ISSUE TITLE
REQUEST: Please put font size change in archtitus.sh

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#169]
It seems it would be much better to change the font size at the very very beginning. Therefore please can you put it in the archtitus.sh script as the very first command to be run

**Comment by godalming123** [comment]
This has been fixed on the latest code

**Comment by godalming123** [comment]
in https://github.com/ChrisTitusTech/ArchTitus/commit/2661c36ce726777597b3512a73377c77fb3871d5#diff-9ce9f41a7bb7e021eec284cdeffa8adcde04f9da68eb75f145cf43dde7285877

**Comment by yehonatan2020** [comment]
yeh I noticed thanks
