### ISSUE TITLE
Feature Request: installation on a partition 

### ISSUE THREAD

**Issue by HARI47737** [ChrisTitusTech/ArchTitus#17]
please add the function for installing on a partition instead of installing on a whole Ssd or Hdd and also support for dual boot. and also a feature for selecting home partition manually

**Comment by Hitalone** [comment]
You can very well do that but you have to just make an empty partition in windows like D:/ but be sure that it is empty then when you run the script it will show you the option inside of /dev/sda for me it was /dev/sda3 and the choose the partition according to the size that you allocated and you can now proceed.

**Comment by ostarch** [comment]
> You can very well do that but you have to just make an empty partition in windows like D:/ but be sure that it is empty then when you run the script it will show you the option inside of /dev/sda for me it was /dev/sda3 and the choose the partition according to the size that you allocated and you can now proceed.

You mean selection of partition (/dev/sda1/) instead of Drive (/dev/sda/) will do that?

**Comment by HARI47737** [comment]
i requested for that . on that video,titus said that select the device which you want to install . I can't do that . because my drive contains windows and some personal data . so after making a free  partition , am I able for the installation ? .(/dev/sda5 instead of /dev/sda)

**Comment by HARI47737** [comment]
> > You can very well do that but you have to just make an empty partition in windows like D:/ but be sure that it is empty then when you run the script it will show you the option inside of /dev/sda for me it was /dev/sda3 and the choose the partition according to the size that you allocated and you can now proceed.
> 
> You mean selection of partition (/dev/sda1/) instead of Drive (/dev/sda/) will do that?

i requested for that . on that video,titus said that select the device which you want to install . I can't do that . because my drive contains windows and some personal data . so after making a free partition , am I able for the installation ? .(/dev/sda5 instead of /dev/sda)

**Comment by d4ve10** [comment]
No, you can currently only specify the whole drive. When specifying a partition (e.g. `/dev/sda5`), the script tries to create partitions inside the partition like `/dev/sda51`.

**Comment by aRealCyborg** [comment]
> No, you can currently only specify the whole drive. When specifying a partition (e.g. `/dev/sda5`), the script tries to create partitions inside the partition like `/dev/sda51`.

Ahhh ok, I wanted to install on my test laptop system but I didn't want to lose windows because it has programs on it that's license is only for that system.
Hopefully support for dual boot installation/installing on a partition will be added soon.

**Comment by meechgalhuquot** [comment]
I'd love to do this as well, Manjaro is frustrating me a bit but I want to maintain my dual boot on my laptop because of some programs that don't work in Wine. I have my user profile on a separate partition as well so just being able to install to a partition on my laptop would be a super easy switch

**Comment by ostarch** [comment]
> I'd love to do this as well, Manjaro is frustrating me a bit but I want to maintain my dual boot on my laptop because of some programs that don't work in Wine. I have my user profile on a separate partition as well so just being able to install to a partition on my laptop would be a super easy switch

I am currently working on this script, keep patience. You can check The Git Profile.
If you are in hurry... Check git/ostarch/ostarch and run (1-base-install.sh) from my script and for rest you can follow CTT for now
