### ISSUE TITLE
Snapper / snapshots didn't worked with the swapfile on /opt/swap

### ISSUE THREAD

**Issue by thanantonop** [ChrisTitusTech/ArchTitus#170]
Hi,

I want to mention that in the version that you had in the past if the system had less tht 8GB of ram and the swapfile was cerated then the system wasnt able to take snapshots because of the swapfile.
I had solved the issue by removing and deleting the swapfile and re-creating in on a seperate subvolume. 
So keep in mind in next releases or improvements to put the swapfile on a seperate subvolume (on the creation on your first script)and not directly under /opt/swap

Keep the nice work!!! Very amazing and useful installation script.

Best regards,
Thanos

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
