### ISSUE TITLE
Many packages from aur-pkgs file didnt installed by the installation script

### ISSUE THREAD

**Issue by thanantonop** [ChrisTitusTech/ArchTitus#178]
I noticed that many packages from the aur-pkgs file didnt installed by the installatin procedure. In the past with the first scritps all were fine and all the packages were there. 
Some missig packages were the nordic themes (all the nordic packages), zoom, snap-pac.
So when you login to the Arch is missing the Nodic login screen.

**Comment by iNatie** [comment]
I see this issue too, I just get yay installed and nothing else from the 2-user.sh script.

**Comment by iNatie** [comment]
![chroot](https://user-images.githubusercontent.com/62487654/149843699-49fd3bdb-c64a-4f96-8bf2-0e5109a6ff2f.JPG)

**Comment by ChrisTitusTech** [comment]
Fixed in latest overhaul.
