### ISSUE TITLE
Norwegian Keyboard 

### ISSUE THREAD

**Issue by hengamer03** [ChrisTitusTech/ArchTitus#187]
i would think -no in the setup means norwegian, well it doesnt work so i dont get the norwegian keyboard laybout on my arch VM

**Comment by vic1707** [comment]
I'm aware of this, and in fact there are 2 problems.
First there shouldn't be a leading `-` (the script should tell this) and the second problem is that the keyboard setup by the script only affects the arch instance used to install archtitus. It doesn't persist upon reboot.

I made a pull request with a dirty fix for it https://github.com/ChrisTitusTech/ArchTitus/pull/184.
You can either clone my branch with the fix or wait for the pull request to be accepted 😉.

**Comment by hengamer03** [comment]
ok thanks, another problem i encountered now is that i get and old version of the script when selecting the keyboard layout before doing the script, sicne when its done installing i get the KDE plasma desktop enviorment, with non vanilla KDE apps like the brave browser already installed. 
![image](https://user-images.githubusercontent.com/97841938/149676855-6515dcc2-2ec9-4058-99de-919bcf155025.png)

**Comment by godalming123** [comment]
This has been fixed in https://github.com/ChrisTitusTech/ArchTitus/pull/191 which has been merged into the testing branch
