### ISSUE TITLE
when getting mirror by curl

### ISSUE THREAD

**Issue by mfgbhatti** [ChrisTitusTech/ArchTitus#188]
i noticed that [curl command](https://github.com/ChrisTitusTech/ArchTitus/blob/5721dbc578e290a1e3e733832bf9eaff8ba79626/0-preinstall.sh#L26) is fetching whole html page.  can anyone verify it.  I am getting same result on my main driver and in qemu when i was testing. the solution seems to use https protocol

**Comment by khaneliman** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/1778670/149671788-ae6117df-0a1a-4ab3-9449-e0e7eb3397fa.png">

**Comment by stojshic** [comment]
Works fine in here, also, I'm getting my country code...

**Comment by mfgbhatti** [comment]
yes i know but this is what i am getting through curl. somehow cloudflare is sending this page
![Screenshot from 2022-01-21 14-14-43](https://user-images.githubusercontent.com/13787498/150544383-01d1d00d-f98c-44df-af02-ec8a6ea116f3.png)

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
