### ISSUE TITLE
Feature request: allow minimal instillation

### ISSUE THREAD

**Issue by godalming123** [ChrisTitusTech/ArchTitus#19]
I would like an option to have a minimal installation as I do not want kde and I'm not forking this on github as I have a problem with how you lay out the pkdgs and am scared of making the script fail. In my opinion you should organise pkdgs as a list of core pkdgs these would include the base, linux and linux-headers etc and a list of extra packdges these are packadges you add to becuase you use them like kde or steam. This would allow me to safely remove all the extra packadges without worry and add custom ones. But thats a completely seperate issue.

**Comment by godalming123** [comment]
I think you can get most of this functionality by using https://github.com/ChrisTitusTech/ArchTitus/tree/server but theres still a few things that it installs such as:
- yay
- a grub theme

**Comment by stojshic** [comment]
Hi. I'm working on a model of the script which will have the option to choose from number of desktop environments, or none. Also few different aur helpers, and also there the option of no aur helper. And the third option is to choose if you want minimal installation (only needed files to get GUI), or fully featured version with few different apps needed for everyday use, plus some versions pre-themed. It's still work in progress, but it should be done in a day or two

**Comment by ChrisTitusTech** [comment]
Finally merged this into the main repo.
