### ISSUE TITLE
EFI Bootloader Support

### ISSUE THREAD

**Issue by pog5** [ChrisTitusTech/ArchTitus#194]
Bug/Feature: EFI based machines not booting after installing/EFI Support

**Comment by lsswizard** [comment]
its not booting efi because the uuid is wrong in the fstab for the boot drive.

**Comment by toha1171** [comment]
> its not booting efi because the uuid is wrong in the fstab for the boot partition.

Is this why it's booting in emergency mode without console? What kind of rodeo tricks do I
have to apply this time to get out of this?

**Comment by jcampbell4485** [comment]
i replace the bootloader with the refind bootloader and install all available drivers. i'm still trouble shooting. didn't find any written instructions though.

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
