### ISSUE TITLE
Separate KDE packages from other packages

### ISSUE THREAD

**Issue by DNI9** [ChrisTitusTech/ArchTitus#195]
in the `pacman-pkgs.txt` do something like this instead to better categorize packages, this will also help other people to know what to delete when they're trying to add other DE/WM specific packages.
```bash
## All other packages
grub-customizer
gst-libav
gst-plugins-good
gst-plugins-ugly
gwenview
haveged
htop
iptables-nft
jdk-openjdk
...

## KDE packages
kate
kcodecs
kcoreaddons
kde-plasma-addons
kinfocenter
kscreen
...
```

**Comment by vic1707** [comment]
Our friend @stojshic did exactly that in his branch to allow different desktop environment to be installed.
He's talking about that in #191.
What you're asking will propably be implemented at the same time as his feature.
