### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by mmheydari97** [ChrisTitusTech/ArchTitus#199]
No matter what username and password I choose, I cannot login as the first run after installation. I tried it on VirtualBox and terminal login does not work either.

**Comment by khaneliman** [comment]
I was able to recreate issue, as well with test branch. I saw a change that was added for moving where generating the fstab happens and I'm not sure if it was intended or not. When I boot into the install I can see the /etc/fstab doesn't contain anything other than a couple swapfile entries.

**Comment by ChrisThePCGeek** [comment]
I just ran a setup and was also unable to log in either.  after rebooting and chroot into the install, and manually setting my user's password with passwd i reboot and was able to log in.  I think it has to do with I had a "$" in my password.  Script probably needs an update to handle special characters being in the password entry.

**Comment by meechgalhuquot** [comment]
> I just ran a setup and was also unable to log in either. after rebooting and chroot into the install, and manually setting my user's password with passwd i reboot and was able to log in. I think it has to do with I had a "$" in my password. Script probably needs an update to handle special characters being in the password entry. Note: this is on server branch

I have no special characters in my password and still have the issue, I do not think that has anything to do with it

**Comment by khaneliman** [comment]
This issue seems to be resolved for me with https://github.com/ChrisTitusTech/ArchTitus/pull/204/files#diff-0e319dec65b78b82baff585fa8a6d9131e49e0796bec143d4d3367528af3d6d9

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
