### ISSUE TITLE
Need a little guidance 

### ISSUE THREAD

**Issue by graziel666** [ChrisTitusTech/ArchTitus#207]
I wanna try the server branch on my thinkpad x260 and just add it a windows manager (bspwm) and support for doing basic gaming on it
Which packages should i install first for that?

I played around a little with the regular branch and really loved it, but since I learned bspwm and configure it I'm not using plasma at all, so I wanted to start fresh on this one

**Comment by godalming123** [comment]
Assuming you have succsesfully installed the server branch. You probably want to follow a basic guide like https://duckduckgo.com/?t=ffab&q=bspwm+installation+arch&iax=videos&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZbXQUOwcH08

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
