### ISSUE TITLE
swapfile: no such file or directory

### ISSUE THREAD

**Issue by mfgbhatti** [ChrisTitusTech/ArchTitus#214]
![Screenshot from 2022-01-28 16-52-29](https://user-images.githubusercontent.com/13787498/151589104-62f13e29-dd2f-46a9-883b-906ba52c5680.png)

i was testing and came across this error. This might be due to not using `-p` flag in mkdir command.

**Comment by d4ve10** [comment]
`/mnt/opt` shouldn't be created manually. Check, if there are any other errors above the swapfile part. Seems like the drive couldn't be mounted or Arch couldn't be installed on that drive.

**Comment by khaneliman** [comment]
The -p flag was added to all mkdir commands in https://github.com/ChrisTitusTech/ArchTitus/pull/231 so this shouldn't occur. @ChrisTitusTech
