### ISSUE TITLE
Arch fails to boot

### ISSUE THREAD

**Issue by meechgalhuquot** [ChrisTitusTech/ArchTitus#217]
A few days ago I accidentally bricked my previous install that I made using the version of the script back in November, and when attempting to reinstall Arch on my laptop with the current release, no matter if using the main or testing branch the computer will not finish booting after install. The attached image shows the error I see on boot. CPU-i7-1195G7, no dGPU, installing onto an NVMe SSD ![image](https://user-images.githubusercontent.com/52185596/151773505-97e1c933-87c5-4b3f-acd2-8ffdca8efd40.jpeg)

**Comment by khaneliman** [comment]
Yeah, i've had issues with the fstab generated by a recent change... I either get the can't log in because of btrfs subvolumes not being mapped on EFI or this message on BIOS.

**Comment by Rdr101957** [comment]
I am having this same issue. How do I fix it manually

**Comment by khaneliman** [comment]
> I am having this same issue. How do I fix it manually

You can try this fox and see if it works for you. 

https://github.com/ChrisTitusTech/ArchTitus/pull/200

**Comment by Rdr101957** [comment]
> > I am having this same issue. How do I fix it manually
> 
> You can try this fix and see if it works for you.
> 
> #200

This did not fix it. The problem is Titus put the fstab generation in after mounting the boot partition. So 
1.) Reboot into the install medium
2.) Mount your root partition at /mnt
3.) (Optional) Mount your home partition at /mnt/home
4.) rm /mnt/etc/fstab
5.) genfstab -U -p /mnt >> /mnt/etc/fstab

**Comment by khaneliman** [comment]
> > > I am having this same issue. How do I fix it manually
> > 
> > 
> > You can try this fix and see if it works for you.
> > #200
> 
> This did not fix it. The problem is Titus put the fstab generation in after mounting the boot partition. So 1.) Reboot into the install medium 2.) Mount your root partition at /mnt 3.) (Optional) Mount your home partition at /mnt/home 4.) rm /mnt/etc/fstab 5.) genfstab -U -p /mnt >> /mnt/etc/fstab

Good point, I'm working on another feature and will try and implement generating fstab before mounting boot for that pull request.

**Comment by tmcarter** [comment]
Seeing same issue here when installing BTFRS thru script

**Comment by meechgalhuquot** [comment]
With yesterdays update to the script this issue is still present

**Comment by khaneliman** [comment]
> With yesterdays update to the script this issue is still present

Are you using main or test branch?

**Comment by meechgalhuquot** [comment]
I have tried both @khaneliman

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
