### ISSUE TITLE
Yay not installed

### ISSUE THREAD

**Issue by dvon88** [ChrisTitusTech/ArchTitus#219]
When installing, I can quickly see an error message that pacman failed to install all packages. Upon reboot, I don't get the nice KDE login screen as I did in v1.0, and after logging in, yay is not found. I believe that I also saw that pacman was missing the go dependency, so it didn't install any of the pacman packages. 

Also, my user was not added to the sudoers files, which might be the root of the issue.

**Comment by desatur8** [comment]
came here to see if I messed up something as it was working last week. I installed the server branch but the same problem, user not part of sudoers and yay not installed, i reran the install script and saw a error flying past, but was to fast to catch

something about -f flag not existing?

**Comment by desatur8** [comment]
dvon, check on pull requests, d4ve10 did a pull request as a updated sudo version caused 2-user.sh to sop working.

**Comment by ahmadjehad** [comment]
just tested it 
yay not installed 
[with server branch]

please fix it

**Comment by godalming123** [comment]
This is because of https://github.com/ChrisTitusTech/ArchTitus/pull/189 when ChrisTitusTech merged it even though I have not thorughly tested but this pr: https://github.com/ChrisTitusTech/ArchTitus/pull/222 fixes the bug

**Comment by godalming123** [comment]
Have you tried that pr?

**Comment by godalming123** [comment]
This should be fixed now

**Comment by godalming123** [comment]
The or was merged

**Comment by ahmadjehad** [comment]
ya sorry didn't close this issue yet 

thanks all for helping
