### ISSUE TITLE
my user is not in sudoers file

### ISSUE THREAD

**Issue by ahmadjehad** [ChrisTitusTech/ArchTitus#220]
i didnt find yay 
and tried to install it manually 
my user is not in sudoers file
tried su also 
but it doesn't work with the password i used in the install 

[ in server branch didn't try the master script]

please fix it guys
i appreciate all the efforts

**Comment by BrankdRad** [comment]
Same for me. 

I also recommend asking to confirm the password at creation otherwise if you make a mistake you're locked out.

Thanks for all the work done.

**Comment by d4ve10** [comment]
This happens because the newest sudo version changed the syntax of the sudoers file. You can just add the lines as shown in #218 to fix it until Chris accepts this pull request.

**Comment by towedjumper** [comment]
> This happens because the newest sudo version changed the syntax of the sudoers file. You can just add the lines as shown in #218 to fix it until Chris accepts this pull request.

d4ve10, I am just BARELY getting into arch and have no idea how to do that when I am running Chris' script.  How can I do this and still use his script?

**Comment by towedjumper** [comment]
I settled on forking his project and editing my file.  No idea if I am doing this, WAAAAYYYY off in the weeds here.
