### ISSUE TITLE
Formatting ArchLinux with archtitus.sh with BTFRS results in KDE Failure

### ISSUE THREAD

**Issue by tmcarter** [ChrisTitusTech/ArchTitus#223]
When installing from source script archtitus.sh and opting in for BTFRS in lieu of ext4 FS, KDE will NOT open and gets hung and dropped down to "Emergency Mode" and added issue of sudoers not added, only makes it worse.  I have restarted and reinstalled like 6 times; and am installing on Lenovo i9-SFF, with NVME option.

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
