### ISSUE TITLE
Write basic test's

### ISSUE THREAD

**Issue by godalming123** [ChrisTitusTech/ArchTitus#225]
Would it be possible to write some basic tests that run with github actions (a place to do automation's to check/deploy code) as recently there has been a lot of problems which are fairly important I believe this is mainly because of the large amount of PR's merged lately. Say just a test that checks that the specified AUR helper is installed or checks the script works instead of having to manually check that.

**Comment by ChrisTitusTech** [comment]
Agreed, I've rebased the project and will do more checks this time around.
