### ISSUE TITLE
No bootable devices found

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#230]
Something is wrong again. After installing and rebooting, it says no bootable devices found

**Comment by yehonatan2020** [comment]
when i went in and mounted the partitions and then ran arch-chroot after running grub-mkconfig, it does not find any operating systems. the only entry that appears in grub now is UEFI firmware settings

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
