### ISSUE TITLE
KDE packages

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#233]
Chris, please add these essential pacman packages to make KDE more complete...

karchive
kauth
kcompletion
kdialog 
kgamma5
khotkeys
kwalletmanager
kwayland-integration
kwrited

**Comment by khaneliman** [comment]
I recognize the benefit in installing a couple of these, for sure. I'll create a PR to get a few added. 

But, I'm seeing several of these installed on a fresh installation using the latest test branch:
1. karchive
2. kauth
3. kcompletion

**Comment by yehonatan2020** [comment]
Nice. I didn't see these ones in any of the package lists

**Comment by khaneliman** [comment]
I didn't see them either so they must be installed as a dependency of something.

**Comment by yehonatan2020** [comment]
Ah ha, nice
