### ISSUE TITLE
Error when booting from VM - Unraid: RDRAND gives funky smelling output

### ISSUE THREAD

**Issue by RodriMora** [ChrisTitusTech/ArchTitus#237]
I'm using a VM with VNC graphics with Unraid 6.9.2 stable.

It installs fine but when I reboot after the install I get this error:

RDRAND gives funky smelling output, might consider not using it by booting "nordrand"

![image](https://user-images.githubusercontent.com/5622210/155720195-10c7d707-5f78-4314-9684-f33199576de1.png)

**Comment by khaneliman** [comment]
Sounds like an AMD bug https://arstechnica.com/gadgets/2019/10/how-a-months-old-amd-microcode-bug-destroyed-my-weekend/ .

**Comment by RodriMora** [comment]
How would I go about addind the nordrand to kernel options? I did a google search  but didn't find the answer.

I have to use an old BIOS version for my mobo as later versions of AGESA causes "error 43" with GPU passthough

**Comment by khaneliman** [comment]
https://wiki.archlinux.org/title/kernel_parameters#GRUB

**Comment by RodriMora** [comment]
I've tried but it didn't work. It's correctly done like this?: 
![image](https://user-images.githubusercontent.com/5622210/155836068-2478936c-caf6-4806-acbd-b381ef94638e.png)

it says it cant find command "nordrand"

**Comment by khaneliman** [comment]
Your supposed to add it to the end of the Linux command line after splash.

**Comment by RodriMora** [comment]
Now the error doesn't print but I'm just stuck at "starting version 250..."

![image](https://user-images.githubusercontent.com/5622210/155847349-66ed3318-c4b9-48c7-8f5b-9c3d5311bbf6.png)

updating the bios might be the only solution... :(

**Comment by RodriMora** [comment]
I
> Can you access tty from there? Ctrl + alt + f3.

Yes, I can. And I can log in with my normal user (not root I believe)

PS: thank you so much you btw, you're Pull request is awesome. You're a genious.

**Comment by khaneliman** [comment]
Can you try taking a look at your journalctl -p err -b

**Comment by RodriMora** [comment]
![image](https://user-images.githubusercontent.com/5622210/155848523-eba5adec-7265-4dfa-8be4-d99b8e4d7503.png)
![image](https://user-images.githubusercontent.com/5622210/155848547-d1412e93-ffd7-453b-ab06-fa3a27d0606e.png)

this helps?

**Comment by khaneliman** [comment]
What graphics card are you using? https://wiki.archlinux.org/title/Kernel_mode_setting#Early_KMS_start

**Comment by khaneliman** [comment]
Hmm I'll try running the latest version of repo on my unraid VM and see if I can get it working there later tonight. I've been using KVM on Arch Linux and I remember having the issue with QXL and needing to use virtio for display instead to get past that error.

**Comment by khaneliman** [comment]
If you remove the quiet and splash from kernel parameters does it behave different?

**Comment by RodriMora** [comment]
I got a bit further, I left it there for more than 5min, it's installed in a passthough'd nvme

![image](https://user-images.githubusercontent.com/5622210/155862652-942746a8-541a-4668-86a2-afb1bbe74d30.png)

**Comment by khaneliman** [comment]
Did you add the Nvidia modules to mkinitcpio.con and rebuild initramfs after changing it to pass through? Or test adding nomodeset to kernel options to see if that helps get into the system, at least.

**Comment by khaneliman** [comment]
When I create a VM on Unraid, I get the `SDDM - Failed to read display number from pipe` when I boot into the TTY through 3 kernel option. The behavior I see without quiet is similar with showing the text just hanging on the boot process. One thing I'm confused on is that I notice it mentioning the libc.so.6 GLIBC 2.34 error that I've only seen to be related to GLIBC incorrect version.

**Comment by RodriMora** [comment]
With an updated BIOS i don't get any error related to CPU bugs now, but I still can boot. I can get to tty though.

This is from a  VM without gpu passthough, your same error:
![image](https://user-images.githubusercontent.com/5622210/155881840-bd1e7069-5c5d-4427-99c4-a4a4e6ab8000.png)

I'll try now with the nvidia parameters you suggested with GPU passthough, let's see if I manageg to configure them properly.

**Comment by RodriMora** [comment]
More stuff I tried now:

With gpu passthough:

I can boot to tty with "3" added to the parameters. I edit with "sudo nano /etc/mkinitcpio.conf" the "MODULES()" an added "nvidia nvidia_modeset nvidia_uvm nvidia_drm" inside the parenthesis. Like this:

MODULES(nvidia nvidia_modeset nvidia_uvm nvidia_drm)

then saved the file and rebuilt  rebuild initramfs with:
mkinitcpio -P

Still the same errors :(

tried adding "random.trust_cpu=on" and "nomodeset" to the options and deleting the "quiet splash" but no difference
