### ISSUE TITLE
Locales are (probably) messed up on gnome install

### ISSUE THREAD

**Issue by calinorg** [ChrisTitusTech/ArchTitus#242]
I've installed new and improved archtitus in a VM (to check for issues before deploying it to main machine), choosing gnome and other options were left as standard (btrfs, nvme, full install etc). Everything went great, i was in gnome in about 10ish minutes, and everything seemed to work great. I tried to open gnome terminal and it failed. It just spinned cursor for a while and then failed to launch. I know that this is usually related to messed-up locales, so I've used your other script to set locales, rebooted and everything started working as it should. I didn't check if this is reproducible in other desktop environments nor did I check what locales were set up prior to firing up your script, sorry...

**Comment by khaneliman** [comment]
Locales are handled separate of any of the current user changeable configurations in the current state of the scripts. Its setup to uncomment out the en_US locale in locale.gen.
`sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen`
 `locale-gen`
  `localectl --no-ask-password set-locale LANG="en_US.UTF-8" LC_TIME="en_US.UTF-8"`
What script did you run to fix the issue?

**Comment by calinorg** [comment]
I've used this gist: https://gist.github.com/ChrisTitusTech/f55e2fd0b39b268fed251d12bd91b5e8

**Comment by Zackptg5** [comment]
@ChrisTitusTech 

This line is needed: `echo "LANG=en_US.UTF-8" > /etc/locale.conf`
