### ISSUE TITLE
Apps and certain ui wont work with wifi connected.

### ISSUE THREAD

**Issue by Phaedom** [ChrisTitusTech/ArchTitus#25]
After installing and entering to desktop everything works fine until a Wifi connection is established, It sits for a few seconds or so then closes. I've tried manually adding a WIfi connection but it persists. I came across another post saying it could have something to do with the host file but I did not try it as it gets a little more technical.

Ryzen 5 5600x
RTX 2070 SUPER
Samsung EVO SSD
Intel AC 8260 wifi card

**Comment by ChrisTitusTech** [comment]
Fixed by changing iwctl but you can also use `nmcli device wifi connect WIFISSID password PASSWORD`
