### ISSUE TITLE
Suggestion: possible to also add an option to user-write config files (build template-ish) for faster install in one command  

### ISSUE THREAD

**Issue by worthless443** [ChrisTitusTech/ArchTitus#254]
The interactive interface is appealing to a lot of people but I (and I hope some other ppl too) might appeal at having a config file to write or download to be able to install in a single command?

**Comment by mfgbhatti** [comment]
Your suggestion is good. But if we are going to act on it then archtitus will be the same script as of [alis](https://github.com/picodotdev/alis/blob/master/alis.conf) and some more already on github.

**Comment by khaneliman** [comment]
I had a similar thought, but all I was going to add was a simple logic check to see if you'd like to use the configuration already provided in the setup.conf file if it's detected. Just to save some short amount of time if you already have the configuration done or are rerunning the script.
