### ISSUE TITLE
Wrong wheel line uncommented in sudoers

### ISSUE THREAD

**Issue by wilsonephillips** [ChrisTitusTech/ArchTitus#258]

**Comment by wilsonephillips** [comment]
Hey Chris, I just ran this installer. I do see an issue that need to be fixed.

In the sudoers file, the wrong line for wheel is commented out. It is allowing wheel without a password.

Thanks!

**Comment by wilsonephillips** [comment]
Not knowing any better, I commented out the one for no password and uncommented the one that asks for a password. The next time I tried to sudo, it did ask for a password, but would not accept my password. Since root seems to be disabled, I am locked out and will have to backdoor in to reset it.

**Comment by yehonatan2020** [comment]
i also noticed this issue. I just put my own username underneath root as opposed to being part of the wheel group

**Comment by wilsonephillips** [comment]
I re-installed and set a password for root before doing the same thing you did.

I see in the script where it is supposed to swap those commented lines, but it is not doing so. It is allowing users to sudo with no password, which could be dangerous.

**Comment by khaneliman** [comment]
The logic is in there to properly set the sudoers file... but I'm assuming if you look at your 3-post-setup.log you will see a syntax error before which will cause it to miss that step. Gonna see if i can get it resolved quickly.

**Comment by yehonatan2020** [comment]
Its supposed to be this way round no?

# Remove no password sudo rights
sed -i 's/^#%wheel ALL=(ALL:ALL) NOPASSWD: ALL/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
# Add sudo rights
sed -i 's/^ %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

**Comment by khaneliman** [comment]
No, it's s/find/replace/. Yours wouldn't change anything.

**Comment by 1c0nnu** [comment]
I noticed the same issue too. I was just lazy and never did anything. If i run those clean up line now in terminal, will that fix the issue?
