### ISSUE TITLE
Zsh not loading its configuration.

### ISSUE THREAD

**Issue by AlexSe9** [ChrisTitusTech/ArchTitus#263]
After installing kde full, zsh its not "seeing" the linked .zshrc in home. 

I had to delete and create the link again so it can work.

**Comment by yehonatan2020** [comment]
yeh i also had this issue

**Comment by khaneliman** [comment]
Looks like the link is incorrect.  
The link points to ~/zsh/.zshrc which resolves to /home/USERNAME/~/zsh/.zshrc.
