### ISSUE TITLE
Feature Request Select language and keyboard layout

### ISSUE THREAD

**Issue by drifter-x** [ChrisTitusTech/ArchTitus#27]
It would be good if language and keyboard layout could be selected before installation.

**Comment by Akitakek** [comment]
That would be nice for sure, the whole world doesn't want en_US necessarily, nor does the whole world use qwerty, or not the same variant of qwerty.

**Comment by Bira-oliverio** [comment]
Please add the instructions to change the keyboard layout on the installation guide and configure the system to use the configured layout.
