### ISSUE TITLE
keyring is not writeable

### ISSUE THREAD

**Issue by hl2guide** [ChrisTitusTech/ArchTitus#277]
I'm installing within VirtualBox and am running into this issue.

ISO:

`archlinux-2022.03.01-x86_64.iso`

I ran the first command:

`pacman -Sy git`

Screenshot:

![VirtualBox_ArchTitus_10_03_2022_22_42_34](https://user-images.githubusercontent.com/17044982/157656390-9f5cbfaf-149e-446d-a19c-b69430a669e1.png)

**Comment by mfgbhatti** [comment]
Try to reload iso or delete the corrupted keys. Reloading iso is easier. I gor thus yesterday. I think it is arch related not ti script

**Comment by hl2guide** [comment]
> Try to reload iso or delete the corrupted keys. Reloading iso is easier. I gor thus yesterday. I think it is arch related not ti script

okay, by reloading do you mean to just reboot and retry?

**Comment by mfgbhatti** [comment]
Sorry for misunderstanding. Yes I was talking about reboot. Which iso you are using? I was on March iso when I got corrupted keys and was on virtualbox. Rebooting managed to remove this problem. 
I came across this problem on arch forum
Try

`pacman -Scc`
`pacman -Syy`
`pacman -Syu`
`pacman-key --init`
`pacman-key --populate`
`pacman-key --refresh-keys`
`pacman -Sy archlinux-keyring`
Hopefully this will help.

**Comment by hl2guide** [comment]
> 

I'll that out and let you know.

**Comment by mfgbhatti** [comment]
Take care.

**Comment by d4ve10** [comment]
@hl2guide try waiting at least 30 seconds before installing git. When you start the archiso, it will update the keyring and trust database in the background.\
You can run `journalctl -f` and wait until it says something like "next trustdb check due at 2022-05-6" and "Finished Initializes Pacman keyring."\
After that, installing git should be working, I had exactly the same problem

**Comment by hl2guide** [comment]
Thanks @d4ve10 I waited 5 minutes then ran the commands and it worked fine.

I wish the README:

- mentioned waiting a few minutes before entering the first command
- mentioned what domains should be allowed through a firewall (ipapi.co, ifconfig.co, ping.archlinux.org, crates.io etc...)
