### ISSUE TITLE
Terminal keeps crashing?

### ISSUE THREAD

**Issue by hl2guide** [ChrisTitusTech/ArchTitus#280]
After a new ArchTitus install the Terminal crashes after each launch.

**Comment by d4ve10** [comment]
You mean the gnome-terminal? Then it is because of locales not correctly set (#242)\
Try running `echo "LANG=en_US.UTF-8" > /etc/locale.conf` and rebooting afterwards

**Comment by hl2guide** [comment]
I used XTerm to run:

`echo "LANG=en_US.UTF-8" | sudo tee /etc/locale.conf`

then restarted. It worked, thanks.
