### ISSUE TITLE
Software app does not function

### ISSUE THREAD

**Issue by hl2guide** [ChrisTitusTech/ArchTitus#281]
![VirtualBox_ArchTitus_14_03_2022_05_22_32](https://user-images.githubusercontent.com/17044982/158073777-beb31c72-99f9-4d37-895a-ab787678581e.png)

**Comment by d4ve10** [comment]
you have to install the package `gnome-software-packagekit-plugin` for it to work

**Comment by hl2guide** [comment]
In XTerm I ran:

`pacman -S gnome-software-packagekit-plugin`

typed `Y`, installed the package and then rebooted.

It worked.
