### ISSUE TITLE
PGP signature issues from thumb drive

### ISSUE THREAD

**Issue by mattloaf** [ChrisTitusTech/ArchTitus#284]
I have noticed an issue this morning with Arch, whether in a VM or physical hardware, when I try to run the first command on the setup it gives me PGP import errors.  I downloaded the ISO from Arch this morning and tried troubleshooting this as much as I could.

This is for every package I attempt to install via pacman

Things tried:

edited /etc/pacman.conf   set SigLevel = Required DatabaseOptional  and DatabaseNever, did not help

tried to initialize the key ring
Removed GPG directory  /etc/pacman.d/gnupg, 
pacman-key --init
pacman-key --populate archlinux...........nothing

pacman -Sy archlinux-keyring......same PGP signature error

Screenshots:

https://i.ibb.co/Wft7zf5/Capture1.png
https://i.ibb.co/k8QFQ1t/Virtual-Box-Arch-Titus-14-03-2022-13-40-14.png

Is anyone else having issues booting Arch from thumb drive and trying to pacman anything?

Thanks much!

**Comment by mfgbhatti** [comment]
Hey there check this #277 out. Your question is answered there. Or just give iso a brief moment to load and then update or install.

**Comment by mattloaf** [comment]
Looks like that did it! I waited about 5 minutes and tried and didnt run into any issues.  Thanks so much for the help!
