### ISSUE TITLE
System not booting after install.

### ISSUE THREAD

**Issue by omar-bdreldin** [ChrisTitusTech/ArchTitus#292]
Hello Chris,
I wanted to thank you for your time and effort to give us this tool.
I was excited to try it out. However I couldn't get the system to boot after installation. I'm trying to setup a Gnome environment.
I tried both full and minimal modes with ext4 file system. Still didn't work, and I get a message that there is no bootable disk.
I suspect grup is the cause as I faced similar issue before, on my laptop, when using the bundled "archinstall" tool.
Can we have the option to not use grup, similar to archinstall?

**Comment by treatmeniceplz** [comment]
I also encountered this

**Comment by omar-bdreldin** [comment]
It seems the "archinstall" tool added a fix for boot failure after installation w/ GRUB on some devices and is now working fine.
The fix was included in their latest version w/ the improved TLI.
However I find the system installation from your script to be much better, I hope this gets fixed in the future.

**Comment by jcampbell4485** [comment]
I encountered this on two other laptops with archtitus, I had installed arch with refind bootloader manually. For another machine I installed artix. Possible theory is both systemd and the grub have initialization functions and by using an operating system that changed one of these on both machines I was able to get the system working. Maybe the windows bootmanager, grub and systemd is conflicting.

**Comment by omar-bdreldin** [comment]
I'm not so sure. The systemd-boot seems to work fine but grub had the issue. 
However distros using grub are working fine for me and you, as you mentioned Artix, so they have a fix for that, and the archinstall team added the fix recently for grub + you have the option to use sytemd-boot.
It would be great if this is fixed in archtitus :)
