### ISSUE TITLE
Add choice to decline themes

### ISSUE THREAD

**Issue by wilsonephillips** [ChrisTitusTech/ArchTitus#294]
Would it be possible to add a choice to the script to decline any added themes?

Thanks so much for all of the work put into this script. This has been a great effort.

**Comment by luqmannn** [comment]
I've also tried to remove the fancy GRUB customization by comment out certain part of the code, but it goes horribly wrong.

**Comment by godalming123** [comment]
Thats because some of the grub code is required to set grub up and part of it is required to theme it
