### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by Mongstaen** [ChrisTitusTech/ArchTitus#296]
Hi! 
Experiencing login loop after installing with this script. 
If correct password, screen turns black then reloads SDDM(?)
If purposefully entering wrong password "login failed"

login works fine in TTY. 
Any ideas?

**Comment by wilsonephillips** [comment]
I already know they are going to ask you for some more information. What Desktop Environment are you logging into. SDDM suggest KDE, but it could be Sway. Also, if KDE, they will want o know if it was Wayland or X11. Did you have a choice there?

**Comment by Mongstaen** [comment]
Hi! 
Sorry, should have mentioned. 

KDE Plasma. Not working on X11 nor Wayland. 

We just changed to summertime here, could that be the culprit?
