### ISSUE TITLE
Hostname problems

### ISSUE THREAD

**Issue by lekrsu** [ChrisTitusTech/ArchTitus#3]
If you're installing with the script on e.g. an usb-tethering connection instead of wifi or ethernet, then the hostname will default to archlinux. If that router you're connecting to already has that registered, then no programs will start since they cant find the display.

The solution to this was to disconnect from WIFI, manually change the hostname in the networkmanager config and in /etc/hosts, then do a reboot.

**Comment by ChrisTitusTech** [comment]
Thanks, I'll be putting a new hostname on this and random digit at end.
