### ISSUE TITLE
Cant use my partition for dualbooting

### ISSUE THREAD

**Issue by lnxm** [ChrisTitusTech/ArchTitus#300]
Hi i want to use Arch Titus instead of archinstall. but there is a problem i want to dualboot but there isnt the option for it. Is there any way to dual boot?

**Comment by mfgbhatti** [comment]
Not really at this moment.

**Comment by jcampbell4485** [comment]
i think this can be done by replacing grub with the refind bootloader. i might try this on my friends laptop currently running refind bootloader with archtitus.

**Comment by rafay99-epic** [comment]
Brother, you can Dual Boot but the condition is that you must have two separate drives. Once Window is one drive and then boot into Linux and start installing the arch Linux. Once your Arch Linux is Installed then you can customize the bootloader to detect the Window Os. Sometimes the bootloader detects the OS it self and sometimes we have to add the Window boot drive to the grub  boot loader
