### ISSUE TITLE
Mirrors issue

### ISSUE THREAD

**Issue by minhook** [ChrisTitusTech/ArchTitus#305]
When switching to US mirrors it causes "failed to rate http(s) download" and same for rsync. i'm new to arch and i'm pretty clueless of what is going on. i'm quite positive it's not ArchTitus but rather arch. any type of help would be amazing :)

**Comment by wilsonephillips** [comment]
There are some of the mirrors that fail, because they just fail. For those that fail, they are left out of the list. It's really nothing to worry about. It is actually proof that the installer is doing what it is supposed to do. :-)

**Comment by minhook** [comment]
> There are some of the mirrors that fail, because they just fail. For those that fail, they are left out of the list. It's really nothing to worry about. It is actually proof that the installer is doing what it is supposed to do. :-)

well, it seems to be a internet issue overall for arch. I am having a hard time understanding it and it seems like nobody else comes across it. When I first load Arch from my USB and use pacman -Sy it takes a long time to load (10-20 minutes). when I use pacman -Syu it works and I am able to install git using pacman -Sy git. When I come to cloning it takes 5 minutes and has a 10% chance of working each time. When it does work, i proceed with the ArchTitus setup where I am then stuck on the setting to US mirrors for a hour+. I am so annoyed with this as I have been trying to get my PC running for 2 days. It says could not resolve host: github.com.

**Comment by wilsonephillips** [comment]
It sounds like you do certainly have some internet issues. Yes, I have some of the mirrors that fail every time I try it. The scripts weeds them out. The more mirrors that timeout, the longer that part will take. I usually only have one or two that fail.

For me, the pacman -Sy will check the keys and sync in a few seconds. The install of git takes less than a minute. The clone of the ArchTitus repo takes only a few seconds as well. The -Syu is checking to see if the ISO needs updating and it really shouldn't. That is why we get a new ISO each month. Besides, it would only update what is running in RAM.

When it tells you that it could not resolve host, that means that DNS is failing to get an IP Address for github.com and that sounds like a issue with your internet link. I don't know if you are running a wired connection or Wi-Fi and this thread is really not the place to go into serious networking problems. It is possible that the ISO just doesn't have a driver that is working properly on your network card.

**Comment by minhook** [comment]
I was wondering if you know a thread that can help me with my issue? and I am using a wired connection.

**Comment by wilsonephillips** [comment]
Right off the top of my head, no.

You might possibly have better support from a different distro. Not all of them have the same drivers on their ISOs. 

And then, the Arch ISO might not be the issue at all. It is also possible that you just have a bad network cable. There are a lot of things that could cause problems. Troubleshooting such things can be a pain.

**Comment by minhook** [comment]
i've used artix and it was meh. i overall just wanted to use arch but i mean if it's going to be this much of a pain in the ass then i guess i'll just go to another distro. thanks anyway :)

**Comment by wilsonephillips** [comment]
I don't know if ezarcher would work any better, but I think it ends up being a vanilla Arch install. I could be wrong on that. I have never used it.

**Comment by rafay99-epic** [comment]
I have the same issue. First Time zone can not be detected and then mirror are not set.
