### ISSUE TITLE
i get thrown into a grub command line on boot

### ISSUE THREAD

**Issue by treatmeniceplz** [ChrisTitusTech/ArchTitus#310]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/75908199/163574952-04333aea-bf7d-46a4-ac51-3da4655cf1a1.png">
ignore my vm name i cant get arch to work

psst i an using 
1024 mb ram
16mb vram
80 gb sata hdd

HELP

**Comment by jcampbell4485** [comment]
try to start the process over probably different distro since not all hardware is supported, as some things vary between culprits. I had a laptop that i needed to replace the bootloader with the refind bootloader and install a few other packages.  If you are distro hopping maybe come back to this. could try the boot repair utility. i think chris also did a video with another utility.

**Comment by treatmeniceplz** [comment]
But it persists on manjaro

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1kbbm4)	[1kbbm4]

On May 23, 2022 at 5:00 GMT, justin ***@***.***> wrote:

try to start the process over probably different distro since not all hardware is supported, as some things vary between culprits. I had a laptop that i needed to replace the bootloader with the refind bootloader and install a few other packages. If you are distro hopping maybe come back to this. could try the boot repair utility. i think chris also did a video with another utility.

**Comment by jcampbell4485** [comment]
a lot of distro's are forks. since you want to try arch again, i would look for an install guide using the refind boot loader and it still might not work. i think the one i followed is a bit dated. you could try reinstalling what was on it, then formatting again.

**Comment by treatmeniceplz** [comment]
It was a clean drive then I tried arch and it didn’t work

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1kbzqf)	[1kbzqf]

On May 23, 2022 at 19:03 GMT, justin ***@***.***> wrote:

a lot of distro's are forks. since you want to try arch again, i would look for an install guide using the refind boot loader and it still might not work. i think the one i followed is a bit dated. you could try reinstalling what was on it, then formatting again.

**Comment by jcampbell4485** [comment]
I llike to use a ventoy for bootable media with added feature.  thiojoe on youtube has a video for how to make one and some info about key file that may be needed for some systems. you have to configure your bios and that varies(ie. legacy support, possibly secure boot) between motherboard. You would also have too look up how to get into your bios maybe hitting delete key after cold boot.

**Comment by treatmeniceplz** [comment]
VirtualBox

**Comment by treatmeniceplz** [comment]
> I llike to use a ventoy for bootable media with added feature. thiojoe on youtube has a video for how to make one and some info about key file that may be needed for some systems. you have to configure your bios and that varies(ie. legacy support, possibly secure boot) between motherboard. You would also have too look up how to get into your bios maybe hitting delete key after cold boot.

VirtualBox

**Comment by treatmeniceplz** [comment]
Any thing else you think is wrong

**Comment by treatmeniceplz** [comment]
The first screenshot I posted is literally a VirtualBox window

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1kcbdj)	[1kcbdj]

On May 23, 2022 at 23:32 GMT, justin ***@***.***> wrote:

I llike to use a ventoy for bootable media with added feature. thiojoe on youtube has a video for how to make one and some info about key file that may be needed for some systems. you have to configure your bios and that varies(ie. legacy support, possibly secure boot) between motherboard. You would also have too look up how to get into your bios maybe hitting delete key after cold boot.

**Comment by jcampbell4485** [comment]
i''ve never found a use for virtual box. it's another layer of complexity. I would not use vm, though try another if you must. maybe it's got to be it's own partition.

**Comment by treatmeniceplz** [comment]
Welll let’s figure it out

**Comment by wilsonephillips** [comment]
Since I cannot see what you did during the install, my first guess would be that the mount point for grub is not the same as the location it was installed to.

Chris' archinstaller is still a work in progress and it is not perfect. A lot of us are using it, but we are editing the script to fit our needs.

The latest ISO of Arch has a pretty good installer built in and you might find it to be simpler for getting your setup working. Just boot the ISO and type archinstall at the command line.

**Comment by jcampbell4485** [comment]
arco linux has some set up instructions for VM on their site under pre-installation. it's probably going to be the same to install archtitus.

**Comment by treatmeniceplz** [comment]
I tried archinstall with grub and nothing

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1lpeqb)	[1lpeqb]

On May 24, 2022 at 15:44 GMT, justin ***@***.***> wrote:

arco linux has some set up instructions for VM on their site under pre-installation. it's probably going to be the same to install archtitus.

**Comment by treatmeniceplz** [comment]
Same issue

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1lpeqi)	[1lpeqi]

On June 19, 2022 at 11:53 GMT, David Dobrzycki ***@***.***> wrote:

I tried archinstall with grub and nothing

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1lpeqb)	[1lpeqb]

On May 24, 2022 at 15:44 GMT, justin ***@***.***> wrote:

arco linux has some set up instructions for VM on their site under pre-installation. it's probably going to be the same to install archtitus.

**Comment by jcampbell4485** [comment]
maybe try artix

**Comment by treatmeniceplz** [comment]
WITH ARCHTITUS

**Comment by jcampbell4485** [comment]
no, try a different os with different package list. i don't think virtual machine is supported in archtitus repo.. bare metal only i think.

**Comment by treatmeniceplz** [comment]
Please give me a download link please

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1lt1gu)	[1lt1gu]

On June 20, 2022 at 3:39 GMT, justin ***@***.***> wrote:

maybe try artix
