### ISSUE TITLE
Question regarding installing ArchTitus

### ISSUE THREAD

**Issue by BlackarchNet** [ChrisTitusTech/ArchTitus#322]
Is ArchTitus' btrfs & Luks filesystem option FDE (Full Disk Encrypted, end to end with only the Boot Partition visible, and when not In use you aren't able to see anything) or Data-at-Rest (only root partition is encrypted and is visible all the time).

**Comment by rafay99-epic** [comment]
I have read the script and there Is no full disk encryption...To my knowledge, you can read the script and there could be a possibility that there might be full disk encryption.
