### ISSUE TITLE
couple issues with framework laptop

### ISSUE THREAD

**Issue by jcampbell4485** [ChrisTitusTech/ArchTitus#324]
upon using menu to restart or shutdown, there will be sometimes a long delay and sometimes error message: 
[   17.182725] watchdog: watchdog0: watchdog did not stop:
[   17.196817] sd-umount[753]: Failed to unmount /oldroot: Device or resource busy
[   17.197269] sd-umount[754]: Failed to unmount /oldroot/dev: Device or resource busy
[   17.197856] shutdown[1]: Failed to finalize file systems, ignoring. 
Not sure if it's something unique to the framework hardware setup or just some issue from distro hops. though everything is working great otherwise. The finger print reader is noted as not supported in the kde settings, though, i was able to get mine working after some trouble shooting.

**Comment by jcampbell4485** [comment]
thank you. the watchdog warning is gone.

**Comment by jcampbell4485** [comment]
I reinstalled the server branch and edited the reboot in systemd.conf file to remove the hash and change the default time to 0. No more failed notes.

**Comment by rafay99-epic** [comment]
to be Honest that is Wired...The framework uses all of the industry standard computer parts so then why is is having trouble starting up or shutdown now... I know that fingerprint scan can be a little difficult to config in Linux as compare to Windows or Mac.

What are the specification of your machine.? 
I would like to order a framework machine and test myself.

**Comment by jcampbell4485** [comment]
8GB ram and I got the intel i5 board. I think it's one of the software packages. The systemd.conf file was related to one of the messages. I think systemd is complaining about a package because the server branch of archtitus worked great without issue. I choose from a post installation script and I can leverage the arch linux tweak tool to hop between desktops.
