### ISSUE TITLE
System Requirements 

### ISSUE THREAD

**Issue by NevGi-cpu** [ChrisTitusTech/ArchTitus#329]
What is the minimum/recommended specs to install ArchTitus.

I have a very old pc
Processor: Intel Duo Core 1.99ghz
Ram: 2gb ddr3
Storage: 320gb hdd

basically all the pre installed hardware that came when i bought with this pc like 7 years ago

**Comment by rafay99-epic** [comment]
Currently. There are no minimum/recommended specification for this Arch Linux Script...I have seen non but you can still install Arch Linux on any OLD laptop or PC,  I have tried installing Arch Linux on my old Laptop and it works. 

### Old Laptop Specification
1. Core i5 2nd Gen
2. Processor: Intel Duo Core 2.0 Gz 
3. 4 GB RAM
4. 250 HDD

 ### Laptop Model:
Laptop Model is Lenovo Think Pad X-220

**Comment by NevGi-cpu** [comment]
How much system resource does it consume can you share a htop/taskmanagers
screenshot with me so i can evaluate it for my old desktop.

**Comment by jcampbell4485** [comment]
depends on what software you want. generally for very low system resources (500MB ram), then the lighter the environment you want. I have plasma with as little as 600MB of ram. awesome may use less resources, though the lxde desktop is intended for lighter systems. I built from the server branch and ran another scropt post installation as well as install the arch linux tweak tool.

**Comment by rafay99-epic** [comment]
You can Install Linux on any thing...It depends what you are going to do...If your task are heavy then sure Your Laptop or PC will slow down or might hang up from time to time. Just install Linux server and install install lower Resource desktop environment. Then you will be good.

**Comment by mfgbhatti** [comment]
Hey,
"Archtitus is a bash script used to automate arch linux installation"
if you go [installation guide](https://wiki.archlinux.org/title/installation_guide#:~:text=Arch%20Linux%20should%20run%20on,2%20GiB%20of%20disk%20space.)

> Arch Linux should run on any [x86_64](https://en.wikipedia.org/wiki/X86-64)-compatible machine with a minimum of 512 MiB RAM, though more memory is needed to boot the live system for installation.[[1]](https://lists.archlinux.org/archives/list/arch-releng@lists.archlinux.org/message/D5HSGOFTPGYI6IZUEB3ZNAX4D3F3ID37/) A basic installation should take less than 2 GiB of disk space.

Though there can be usage limitations as well as desktop environment installation. Upon searching on google, I found this

- GNOME 736 MB Memory used
- KDE 633 MB Memory used
- Cinnamon 631 MB Memory used
- MATE 540 MB Memory used
- Xfce 453 MB Memory used
- LXQt 400 MB Memory used
- LXDE 235 MB Memory used

This can differ, but will give you a little idea about DEs. There is also another option installing just Windows Manager like i3 bspwm, awsome etc. At the end it depends on your usage of the system.
