### ISSUE TITLE
Wifi not connected 

### ISSUE THREAD

**Issue by sanshibu** [ChrisTitusTech/ArchTitus#331]
rfkill list shows nothing. Can’t seem to connect to wifi. iwctl and nothing works. I installed Arch from the latest installer
![image](https://user-images.githubusercontent.com/54126162/174929976-c2b7e503-9270-41a0-9616-939cc827a072.jpg)

**Comment by jcampbell4485** [comment]
Should be able to use nmtui package from terminal

**Comment by mfgbhatti** [comment]
Hey, ArchTitus has nothing to do with wifi setup. But you certainly get help related to arch from
1. [Arch Wiki](https://wiki.archlinux.org/title/Network_configuration/Wireless)
2. [Arch Reddit](https://www.reddit.com/r/archlinux/)
and it is always helpful providing more information like your wifi adaptor, you laptop make, model, about the iso you are using etc etc.
