### ISSUE TITLE
Remove GRUB customization

### ISSUE THREAD

**Issue by luqmannn** [ChrisTitusTech/ArchTitus#332]
How can I **remove fancy GRUB customization** without messing things up. So far I've tried disable certain part of code that related to the customization but ended up horribly wrong. After the reboot, it's either **fail to start Light Display Manager** or **fallback to minimal BASH-like line editing**. What line of code I should specifically comment out without messing things up? If anyone know how to do this, it would be greatly appreciate since I'm new to BASH scripting.

**Comment by jcampbell4485** [comment]
I have used the archlinux-tweak-tool to customize grub, for which you need to install the arcolinux-spices tool. You can add your wall paper.

**Comment by luqmannn** [comment]
@jcampbell4485 Is this the [tool](https://github.com/arcolinux/archlinux-tweak-tool) right?

**Comment by wilsonephillips** [comment]
That is the tool and it is listed in the AUR as archlinux-tweak-tool-git

**Comment by wilsonephillips** [comment]
You can also use the grub-customizer from the official arch repos.

**Comment by jcampbell4485** [comment]
> @jcampbell4485 Is this the [tool](https://github.com/arcolinux/archlinux-tweak-tool) right?

Eric Dubois is the maintainer of the archlinux tweak tool and the github page is a mirror i think. It may have started out on github. I think wilson is right for the official AUR package. The development version is archlinux-tweak-tool-dev-git.

**Comment by joshuataylor** [comment]
If you want to do it before install, you can eiher fork this repo or clone on a fresh install then edit the file before installing:

1. Open `scripts/3-post-setup.sh` (https://github.com/ChrisTitusTech/ArchTitus/blob/main/scripts/3-post-setup.sh#L40)
2. Remove lines 40-52 (as of 2022-07-11 this is:
```bash
echo -e "Installing CyberRe Grub theme..."
THEME_DIR="/boot/grub/themes"
THEME_NAME=CyberRe
echo -e "Creating the theme directory..."
mkdir -p "${THEME_DIR}/${THEME_NAME}"
echo -e "Copying the theme..."
cd ${HOME}/ArchTitus
cp -a configs${THEME_DIR}/${THEME_NAME}/* ${THEME_DIR}/${THEME_NAME}
echo -e "Backing up Grub config..."
cp -an /etc/default/grub /etc/default/grub.bak
echo -e "Setting the theme as the default..."
grep "GRUB_THEME=" /etc/default/grub 2>&1 >/dev/null && sed -i '/GRUB_THEME=/d' /etc/default/grub
echo "GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\"" >> /etc/default/grub
```
It will then not install that theme.

# If you already have this installed
1. Backup /etc/default/grub
2. Open /etc/default/grub
3. Comment out or remove the line `GRUB_THEME="/boot/grub/themes/CyberRe/theme.txt"`
4. Save and exit
5. Run `grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by olivertzeng** [comment]
agreed
