### ISSUE TITLE
theme issue preventing login

### ISSUE THREAD

**Issue by notluka123** [ChrisTitusTech/ArchTitus#333]
this is an issue im facing with the nordic theme, when kde is selected everything works as is should however upon reboot it gives me an error saying the theme is not installed correctly and offers me no other choice of theme thus preventing me from logging in, i have tried the install process multiple times yet the results remain the same

**Comment by mfgbhatti** [comment]
Hey, I can understand it is frustrating, but you need to provide logs generated by script.

**Comment by notluka123** [comment]
Hey, i ended up contacting Chris directly in the meantime and he said that its an issue with the script itself and that it needs to be updated and he will do so as soon as he gets the chance. several issues have appeared since the making of this thread such as an issue with chroot thus my reason for contacting him
