### ISSUE TITLE
Scripts unable to run

### ISSUE THREAD

**Issue by JesseKoldewijn** [ChrisTitusTech/ArchTitus#337]
Hey there, 
I just tried to run the script, but when it gets to the point of moving into the 1-setup script, it fails. I checked if the clone might not have included all the files (you never know) but all the files are there.
![image](https://user-images.githubusercontent.com/60965908/183033036-92d05249-9289-4c60-aa7b-2ad4631fcfc0.png)
As an attempted fix I've changed the root folder from archtitus to ArchTitus as mentioned in the shown error but no dice.

I don't exactly know where to find a fix for this issue even after looking into the scripts myself. Hope one of ya can fix this soon.

**Comment by mfgbhatti** [comment]
Hey there, I think for some reason the script is not mounting you drive at `/mnt`. If you can provide the logs generated by ArchTitus.

**Comment by JesseKoldewijn** [comment]
> 

Hey there, I ended up just installing arch manually. I also don't know for sure where the logs from the script would be placed otherwise I would try to recreate the issue on a VM or old laptop in a heartbeat.

**Comment by gamerking64** [comment]
> Hey there, I think for some reason the script is not mounting you drive at `/mnt`. If you can provide the logs generated by ArchTitus.

I have the same issue like him now after trying it first time here on my laptop with btrfs and kde, im ready to share logs but how?

**Comment by JesseKoldewijn** [comment]
> ![20220824_033645](https://user-images.githubusercontent.com/95878367/186290158-19c21f4b-4cda-4239-8256-1047ce67bb06.jpg) ![20220824_033725](https://user-images.githubusercontent.com/95878367/186290191-dd72f610-ffed-4750-9124-32f09c3ea414.jpg) ![20220824_033747](https://user-images.githubusercontent.com/95878367/186290217-e8649b43-7875-416c-b064-109c9e4c05bf.jpg) ![20220824_034141](https://user-images.githubusercontent.com/95878367/186290231-3b906f58-e497-46c1-8483-f5b2af900893.jpg)
> 
> > Hey there, I think for some reason the script is not mounting you drive at `/mnt`. If you can provide the logs generated by ArchTitus.
> 
> I got the EXACT SAME issue like him now after trying archtitus first time here on my laptop baremetal, i shared all log files i found and setup.conf as shown above in pictures, becoz im in arch live iso and i can't copy these files to my phone so im sorry... Hope issue is clear now, Error seems to be only No Such File Or Directory, so maybe the name of the directory link for the scripts are named differently now? Just guessing.

As mentioned by @mfgbhatti I think the issue would be that the target drive isn't being mounted correctly.

**Comment by gamerking64** [comment]
> 

Now im getting archlinux key errors, i tried everything to fix it and it did work, so now i can't even run pacman -Sy git coz keys not trusted... This is happening with latest current archlinux ISO by default so dunna if that's a guge bug happening with arch rn, i know this is nothing to do with archtitus but very weird so maybe if you can test for me the latest arch iso and if you hv key issues? Thx btw

**Comment by JesseKoldewijn** [comment]
> Did you run pacman-key init and do you have the correct timezone setup?

**Comment by JesseKoldewijn** [comment]
> > 
> 
> Now im getting archlinux key errors, i tried everything to fix it and it did work, so now i can't even run pacman -Sy git coz keys not trusted... This is happening with latest current archlinux ISO by default so dunna if that's a guge bug happening with arch rn, i know this is nothing to do with archtitus but very weird so maybe if you can test for me the latest arch iso and if you hv key issues? Thx btw

And did you get the latest archlinux keyring?

**Comment by gamerking64** [comment]
I tried everything including pacman-key --init, btw i know alot of archlinux and im from the XeroLinux team... Anyways i tried installing iso again and still same issue, i tired everything in my mind including removing the check for keyring from pacman.conf...

**Comment by gamerking64** [comment]
Most likely its an archlinux problem now with there iso, unless its something bout my ISP? When you can install and test latest arch iso for me plz just to verify

**Comment by JesseKoldewijn** [comment]
> I tried everything including pacman-key --init, btw i know alot of archlinux and im from the XeroLinux team... Anyways i tried installing iso again and still same issue, i tired everything in my mind including removing the check for keyring from pacman.conf...

Yeah sorry man, just tryna think with ya. Wasn't trying to talk down on ya in any way 😄

**Comment by gamerking64** [comment]
> > I tried everything including pacman-key --init, btw i know alot of archlinux and im from the XeroLinux team... Anyways i tried installing iso again and still same issue, i tired everything in my mind including removing the check for keyring from pacman.conf...
> 
> Yeah sorry man, just tryna think with ya. Wasn't trying to talk down on ya in any way 😄

Don't be sorry i was just saying it to let you know that i tried almost everything, coz nothin 100% in this world ofc, now since its an arch issue not archtitus will wait until i know what's the issue, then comeback and continue, but i found something strange, what's the difference between: -git clone https://github.com/ChrisTitusTech/ArchTitus
And 
-git clone https://github.com/christirustech/archtitus

**Comment by gamerking64** [comment]
Will test the second url coz i used thw one found in readme on github before the archlinux key thing happened, so again when the issue will get fixed will try archtitus with the url shown in vids (lowercased letters) lol
