### ISSUE TITLE
Question about drivessd function in startup.sh

### ISSUE THREAD

**Issue by Tuchdov** [ChrisTitusTech/ArchTitus#352]
I'm not very experienced in coding, but if the action is the same in both cases (lines 272,274) isn't this function redundant?
Here's a screenshot:
![image](https://user-images.githubusercontent.com/98708027/191241879-b348859b-2d9e-4d57-8ff6-911cd76a66e4.png)

**Comment by EliteCodexer** [comment]
The mount options are not the same though. Notice the 'ssd' option if yes

**Comment by Tuchdov** [comment]
@EliteCodexer Got it, thanks!
