### ISSUE TITLE
Out of Memory C++ Fatal Errors

### ISSUE THREAD

**Issue by Clisty1973** [ChrisTitusTech/ArchTitus#39]
Hey Chris, getting lost of fatal errors C++ out of memory and killing processes etc. Install takes over an hour to complete, (330mb internet connection )and I am missing the wifi in the taskbar, unable to adjust screen brightness on the laptop.
laptop has 8gb of ram but obviously some of that ill be allocated to the APU.
screenshot attached.
![20211026_144901](https://user-images.githubusercontent.com/77356385/138894397-9177eba6-da54-4cdf-b407-7dbe32b85e46.jpg)

**Comment by ChrisTitusTech** [comment]
Fixed in latest update
