### ISSUE TITLE
Feature Request: Encrypted Setup

### ISSUE THREAD

**Issue by 71Zombie** [ChrisTitusTech/ArchTitus#4]
This isn't an issue, just a request. I'd really like to see an encrypted partition install, having a system unencrypted is a major concern on mobile devices. It's possible to create an encrypted BTRFS partition from my research.

**Comment by 71Zombie** [comment]
> Hi i have created a encryption function with luks in my fork of the script, https://github.com/EnigmaDR/ArchTitus/blob/main/0-preinstall-luks.sh and i added configuring mkinitcpio in 1-setup.sh.

Make a pull request?

**Comment by ChrisTitusTech** [comment]
Added
