### ISSUE TITLE
Feature Change: Discover remove and pamac add

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#45]
Please add pacman packages...
plasma-nm bluez-utils dtc extra-cmake-modules  gwenview filelite kcodecs kcoreaddons kde-plasma-addons kinfocenter kscreen libdvdcss powerdevil python-notify2 python-psutil python-pyqt5

Please add aur package..
lightlyshaders-git

**Comment by t9999clint** [comment]
Could you also add pamac-full and remove plasma-discover
I'm still pretty new to arch (litterally just switched to it using your script) so I don't know the exact package names.

**Comment by t9999clint** [comment]
Just noticed now that filelite is spelt wrong. It's filelight

Also the one I wanted you to add is pamac-all from the aur. not pamac-full
looks plasma-discover is just called discover on arch. It's completly broken on your arch setup so It's probably just better off removing it in favor of pamac

**Comment by ChrisTitusTech** [comment]
fixed all that. I'll swap from discover to pamac qt in the future

**Comment by Locutus64** [comment]
@t9999clint Discover isn't broken in Arch, it's just that it does not handle everything Pamac-all can. @ChrisTitusTech is there any chance of posting here or somewhere so we can get notified when you've updated the script? I want to test on my machine and see if it hangs at login screen like my roommates did, but I want to wait till Discover is replaced. As for Pamac @t9999clint is right Pamac-all is a better choice or the below packages. I've heard that on some Arch distros Pacman-all can be a problem. Thanks

```
pamac-gtk
pamac-cli
pamac-tray-plasma
libpamac
libpamac-flatpak-plugin
libpamac-snap-plugin
```

**Comment by ChrisTitusTech** [comment]
Probably would want to use pamac-qt instead of gtk since this is KDE after all.

**Comment by yehonatan2020** [comment]
octopi-dev and octopi-notifier-frameworks would be a nice choice instead of pamac

**Comment by ChrisTitusTech** [comment]
Options now exist in the script to do this.
