### ISSUE TITLE
I know that's an automate script but

### ISSUE THREAD

**Issue by scardracs** [ChrisTitusTech/ArchTitus#61]
I was reading the script and at preinstall I've found something "weird"?

1) Why the 1st partition is 0->+1000M? Does not sgdisk use M as MB like others partition managers?
2) You're supposing the OS is installed on a UEFI PC when it could not: the setup is clearly OK but, as said, only on an UEFI PC.
3) As I see lots of time, 100/150MB is enough for /boot partition, more space is a waste of free space for /.
4) I'd suggest to add the possibility to use btrfs instead of ext4 (and add subvolumes like root and home).
5. I'd suggest to make a file with all the $ stored (for eg $HOMESCRIPT=...). On that way you have not to worry about "I've changed it on all the files?" and save you from a lot of pain in ass

For reference at point 1 and 2: https://github.com/ChrisTitusTech/ArchTitus/blob/a372b52c56f3f88ab6a9143639f5b09d89cf3a0b/0-preinstall.sh#L59L61

**Comment by ChrisTitusTech** [comment]
Fair enough, I'll tone the boot down to 100.

**Comment by ChrisTitusTech** [comment]
it already uses btrfs and subvolumes ;)

**Comment by ChrisTitusTech** [comment]
GRUB change has been submitted to test, I just need to test it.

**Comment by scardracs** [comment]
> it already uses btrfs and subvolumes ;)

Isn't 8300 ext4? https://github.com/ChrisTitusTech/ArchTitus/blob/a372b52c56f3f88ab6a9143639f5b09d89cf3a0b/0-preinstall.sh#L65

**Comment by ChrisTitusTech** [comment]
thats partition type, NOT filesystem type.

**Comment by scardracs** [comment]
> thats partition type, NOT filesystem type.

Ah yes, my bad 😅
