### ISSUE TITLE
Change to Paru from Yay

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#64]
Can you change things to use Paru instead of Yay, as apparently Paru will take over as default  at some point. Maybe an idea to create a symlink to paru, so that people who are still familiar with yay, could issue the yay command, and it would simply point to Paru. I edited the user.sh script and can confirm that using Paru for the aur packages works.

**Comment by yehonatan2020** [comment]
git clone "https://aur.archlinux.org/paru.git"
cd ${HOME}/paru
makepkg -si --noconfirm

for PKG in "${PKGS[@]}"; do
   paru  --color=always -S --noconfirm $PKG
done

**Comment by ChrisTitusTech** [comment]
I don't really like paru is the problem... the script review and other aspects aren't ideal for me. I'll probably switch eventually, but I just don't see any advantage to using paru.
