### ISSUE TITLE
Is this using grub at all?

### ISSUE THREAD

**Issue by purplesanz** [ChrisTitusTech/ArchTitus#69]
I'm trying to add the kernel parameter **mitigations=off** to **/etc/default/grub**, but then when I try to update grub, it doesn't let me. I also wanted to try Xanmod kernel, but since I do not get a grub welcome screen, I cannot select another kernel, which complicates things for me. Is there anything I can do to make it work? I know these are probably very noobish questions, so I apologize in advance, I just would really like to use this "distro".

**Comment by ChrisTitusTech** [comment]
Yes I switched to GRUB in the last commit earlier today. 
I'd recommend using grub-customizer, it's already installed and it has a GUI.
