### ISSUE TITLE
Feature Request: File System - Hostname - Swap File (Fix submitted to test branch)

### ISSUE THREAD

**Issue by IAmHugh001** [ChrisTitusTech/ArchTitus#7]
I noticed in your video you didn't indicate which file system. Nor did you indicate how many partitions this sets up. I normally go for BTRFS on a single partition with the 200 to 500 meg fat 32 boot partition preceding that. I currently do not have a swap partition or swap file. Thanks for any info.

**Comment by ChrisTitusTech** [comment]
Partitions are btrfs (EFI + Root) with subvolume labeled @
I don't use swap on these, but probably a good idea to add it. Since there is very little difference between swap partitions and files, I'll add a swap file in the post setup.
