### ISSUE TITLE
Virtual Machine Manager

### ISSUE THREAD

**Issue by w9hdg** [ChrisTitusTech/ArchTitus#75]
I tried to create a VM tonight using Virtual Machine manager. I had to start/enable libvirtd and now I can't get past the networking step. I tried installing dnsmasq bridge-utils openbsd-netcat as indicated by the ArchWiki with no sucess
![Screenshot_20211102_192151](https://user-images.githubusercontent.com/4405759/139969168-49cc72ae-2afa-405b-acdc-6a6803a283e6.png)
![Screenshot_20211102_192213](https://user-images.githubusercontent.com/4405759/139969169-900e9565-05e1-489d-a29f-b3fdbfcebd2f.png)
.

**Comment by d4ve10** [comment]
First of all, your user should be added to the libvirt group. To do so, run the following command:
`sudo usermod -a -G libvirt $(whoami)`

See if the network is active by running
`sudo virsh net-list --all`
If it's inactive, you can start the network with
`sudo virsh net-start default`
or let it autostart with
`sudo virsh net-autostart default`
