### ISSUE TITLE
1-setup.sh Not found 

### ISSUE THREAD

**Issue by SXehcusF** [ChrisTitusTech/ArchTitus#77]
![16359506683533705532481218171250](https://user-images.githubusercontent.com/93664351/140082677-700c1023-78a6-4ec3-a51a-af6726f433ba.jpg)
After I formatted my drive

**Comment by 0TTA** [comment]
I have the same issue form:
I7700K
1070
I got the same thing, when I tried it with VM in UNraid.

**Comment by hmne** [comment]
Yep same for me
I wish there is option to install to partition not full disk

**Comment by ChrisTitusTech** [comment]
Might switch from BTRFS as subsequent runs can lead to this.

**Comment by KodyVB** [comment]
@ChrisTitusTech When I was making my own installation scripts about a year ago, I was running into problems with automating the btrfs setup as well. I found that chaining all the file system creation, mounting, and subvolume creation commands together with `&&`'s solved my problems, so it might be worth a shot to try that. I think just having them on separate lines had one part or another starting before the previous part finished. 

For clarity, this is the part from my scripts (`$PN2` is the btrfs partition and `$PN1` is the EFI partition for my script):
```
mkfs.vfat $PN1 &&
	mkfs.btrfs -f $PN2 &&
	mount $PN2 /mnt &&
	btrfs subvolume create /mnt/@ &&
	btrfs subvolume create /mnt/@home &&
	btrfs subvolume create /mnt/@var_log &&
	umount /mnt &&
	mount -o noatime,compress=zstd,space_cache=v1,discard=async,subvol=@ $PN2 /mnt &&
	mkdir -p /mnt/{boot/EFI,home,var/log,mnt/rpool} &&
	mount -o noatime,compress=zstd,space_cache=v1,discard=async,subvol=@home $PN2 /mnt/home &&
	mount -o noatime,compress=zstd,space_cache=v1,discard=async,subvol=@var_log $PN2 /mnt/var/log &&
	mount -o noatime,compress=zstd,space_cache=v1,discard=async $PN2 /mnt/mnt/rpool &&
	mount $PN1 /mnt/boot/EFI ||
	exit 1
```

They could be separate issues, but I do remember my problems arose specifically when I was running the script on what was already a btrfs setup previously.

**Comment by 71Zombie** [comment]
I just ``sudo chmod +x`` all the files and it works for me.

**Comment by hmne** [comment]
> I just `sudo chmod +x` all the files and it works for me.

Nop it's not working

**Comment by oguh43** [comment]
same issue

**Comment by 71Zombie** [comment]
I did chmod +x for every single file then running sudo bash archfi and it works for me

**Comment by ChrisTitusTech** [comment]
fixed with latest commit
