### ISSUE TITLE
When i reboot out of the installation this comes up and i dont know what to do help

### ISSUE THREAD

**Issue by Minethegroud** [ChrisTitusTech/ArchTitus#79]
![16359722985465859551541149046540](https://user-images.githubusercontent.com/63200516/140189935-e41e1703-da71-46e2-a90f-f2484302e6a8.jpg)

**Comment by DanielToubul** [comment]
same, seems like the grub installation is broken in the current script version.

**Comment by Minethegroud** [comment]
How long will it take to be fixed

**Comment by DanielToubul** [comment]
we have to wait for the master @ChrisTitusTech  to tell us the answer

**Comment by d4ve10** [comment]
Doesn't seem like grub is the problem here. This is the screen that you see after grub while waiting for the system to boot.
What you can do is get more details of the boot.
You can do that by pressing 'e' at the grub menu, and replace 'quiet' with 'text'

**Comment by Minethegroud** [comment]
I,ll try that in vmware

**Comment by ChrisTitusTech** [comment]
My bad, I did an upgrade and moved the BIOS GRUB install outside chroot and forgot to fix the directory. Should work now.

**Comment by raulidg33** [comment]
I just did a fresh install and got this same screen
