### ISSUE TITLE
cant install on vmware workstation

### ISSUE THREAD

**Issue by riversde** [ChrisTitusTech/ArchTitus#8]
Not installing system token, since we are running in a virtualized environment. 
Created EFI boot entry "Linux Boot Manager",
cp: cannot stat '/etc/pacman.d/mirrorlist': No such file or directory......

**Comment by riversde** [comment]
neither on virtual box, same error trying to make partitions.

**Comment by njscorpion** [comment]
I am a Linux noob, however I was able to install it on virtual box,  did not try VMware. During the installation when the script prompts for selecting a disk type in /dev/sda, earlier i typed sda only and threw some error. Hope it helps!

**Comment by ChrisTitusTech** [comment]
Updated to compensate for low end system and legacy boot now works
