### ISSUE TITLE
powerpill

### ISSUE THREAD

**Issue by qualk** [ChrisTitusTech/ArchTitus#85]
can there please be an option to use chaotic-aur and powerpill?

**Comment by WitherCubes** [comment]
Chaotic AUR is a bit unstable (some packages break in there), and new users will get confused to install from chaotic AUR or the regular AUR. Powerpill in unnecessary because pacman now has a default parallel downloads option. If new users want to go that deep, they can do it on their own.

**Comment by qualk** [comment]
Oh damn, didn't realise that `pacman` already had the option for parallel downloading.
