### ISSUE TITLE
Mirrors are not always available

### ISSUE THREAD

**Issue by amatosg** [ChrisTitusTech/ArchTitus#91]
In my case, the $iso variable is PE, but as there is no mirror, the installation fails. I found that CL works, so I had to change the $iso value to CL and everything worked.

Solution: use a fallback mirror in case there is no mirror for the $iso value

**Comment by cwaku** [comment]
@amatosg I'm stuck on same issue and I'm new to arch,  how do I do that too please?

**Comment by cwaku** [comment]
> @amatosg I'm stuck on same issue and I'm new to arch, how do I do that too please?

Never mind I solved it.... In my case I found out that the mirrorlist was being moved instead of copying when backing up... I forked and did the changes and everything is fine now.

Someone already raised an issue about it. Hope they do necessary changes to main

**Comment by ChrisTitusTech** [comment]
Just did a commit to fix this.
