### ISSUE TITLE
Feature Request: Installing on System with legacy Boot

### ISSUE THREAD

**Issue by fritzchentastig** [ChrisTitusTech/ArchTitus#92]
Hi 
I’m using old PC a lot. And sadly they have legacy boot so I can’t use the script. Would it be possible to add the option of legacy boot? This would easy my life a lot. 

Sincerely 
fritzchentastig

**Comment by d4ve10** [comment]
This is currently possible. The script checks if you are in Legacy or UEFI Boot and installs it accordingly.
