### ISSUE TITLE
Username Password name of machine error

### ISSUE THREAD

**Issue by Lasereliten** [ChrisTitusTech/ArchTitus#94]
I ran the script and when i came to enter a username i get "username does not exist" and then it straight jumps to naming the machine, i name the machine and it sats "error" then finishes the installation and prompts me to eject the media and reboot, i reboot and eject the media and fire up arch. I am then welcomed with a screen that says Select your user and enter password. And i cant click anywhere and i am stuck on this screen.

What went wrong? i have retried this installation 4 times now and i end up with the same result every time.

**Comment by d4ve10** [comment]
Which username did you try?

**Comment by Lasereliten** [comment]
> Which username did you try?

I reinstalled it again at home with a different internet connection, then it worked flawlessly! I've tried it out for a couple of hours now and i went back to Pop os. I couldn't get Battle.net working, it wouldn't connect... 

I am looking forward to debian titus however, will try that out as well when he is done with it!
